import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "@/components/navigation/navigation";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ padding: "16px" }}>
        {/* this is the header where we import the navigationc omponent
        This is to make sure, that our whole app shares the same layout
        and has access to the navigation.
        If an app has several different layouts, such as login which
        does not have a navigation, you need to create
        layout groups. And each layout group has its own shared
        layout-component, which is only viable in that group where
        it is
        */}
        <header>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
